Ext.define('FixedSummary.store.Users', {
    extend     : 'Ext.data.Store',
    requires   : 'FixedSummary.model.Users',
    model      : 'FixedSummary.model.Users',
  remoteSort : false,
	data 	   : [
		{ "id":"1","Name":"Nick","Surname":"Nick","Maths":"12","Physics":"15","Chemistry":"17","Biology":"12","Absences":"12","Papers":"10"},
		{ "id":"2","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"18","Chemistry":"12","Biology":"12","Absences":"15","Papers":"1"},
		{ "id":"3","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"10","Chemistry":"12","Biology":"13","Absences":"21","Papers":"0"},
		{ "id":"4","Name":"Nick","Surname":"Nick","Maths":"14","Physics":"11","Chemistry":"19","Biology":"15","Absences":"5","Papers":"2"},
		{ "id":"5","Name":"Nick","Surname":"Nick","Maths":"10","Physics":"19","Chemistry":"20","Biology":"17","Absences":"0","Papers":"2"},
		{ "id":"6","Name":"Nick","Surname":"Nick","Maths":"20","Physics":"17","Chemistry":"11","Biology":"17","Absences":"20","Papers":"8"},
		{ "id":"7","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"8","Name":"Nick","Surname":"Nick","Maths":"17","Physics":"13","Chemistry":"20","Biology":"19","Absences":"35","Papers":"12"},
		{ "id":"9","Name":"Nick","Surname":"Nick","Maths":"18","Physics":"10","Chemistry":"17","Biology":"11","Absences":"56","Papers":"12"},
		{ "id":"10","Name":"Nick","Surname":"Nick","Maths":"11","Physics":"20","Chemistry":"20","Biology":"20","Absences":"45","Papers":"20"},
		{ "id":"11","Name":"Nick","Surname":"Nick","Maths":"19","Physics":"18","Chemistry":"14","Biology":"16","Absences":"8","Papers":"5"},
		{ "id":"12","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"17","Chemistry":"16","Biology":"18","Absences":"9","Papers":"8"},
	    { "id":"13","Name":"Nick","Surname":"Nick","Maths":"20","Physics":"17","Chemistry":"11","Biology":"17","Absences":"20","Papers":"8"},
		{ "id":"14","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"15","Name":"Nick","Surname":"Nick","Maths":"17","Physics":"13","Chemistry":"20","Biology":"19","Absences":"35","Papers":"12"},
		{ "id":"16","Name":"Nick","Surname":"Nick","Maths":"18","Physics":"10","Chemistry":"17","Biology":"11","Absences":"56","Papers":"12"},
		{ "id":"17","Name":"Nick","Surname":"Nick","Maths":"11","Physics":"20","Chemistry":"20","Biology":"20","Absences":"45","Papers":"20"},
		{ "id":"18","Name":"Nick","Surname":"Nick","Maths":"19","Physics":"18","Chemistry":"14","Biology":"16","Absences":"8","Papers":"5"},
		{ "id":"19","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"17","Chemistry":"16","Biology":"18","Absences":"9","Papers":"8"},
		{ "id":"20","Name":"Nick","Surname":"Nick","Maths":"19","Physics":"12","Chemistry":"12","Biology":"12","Absences":"1","Papers":"2"},
		{ "id":"21","Name":"Nick","Surname":"Nick","Maths":"14","Physics":"11","Chemistry":"19","Biology":"15","Absences":"5","Papers":"2"},
		{ "id":"22","Name":"Nick","Surname":"Nick","Maths":"10","Physics":"19","Chemistry":"20","Biology":"17","Absences":"0","Papers":"2"},
		{ "id":"23","Name":"Nick","Surname":"Nick","Maths":"20","Physics":"17","Chemistry":"11","Biology":"17","Absences":"20","Papers":"8"},
		{ "id":"24","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"25","Name":"Nick","Surname":"Nick","Maths":"17","Physics":"13","Chemistry":"20","Biology":"19","Absences":"35","Papers":"12"},
		{ "id":"26","Name":"Nick","Surname":"Nick","Maths":"12","Physics":"15","Chemistry":"17","Biology":"12","Absences":"12","Papers":"10"},
		{ "id":"27","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"18","Chemistry":"12","Biology":"12","Absences":"15","Papers":"1"},
		{ "id":"28","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"10","Chemistry":"12","Biology":"13","Absences":"21","Papers":"0"},
		{ "id":"29","Name":"Nick","Surname":"Nick","Maths":"14","Physics":"11","Chemistry":"19","Biology":"15","Absences":"5","Papers":"2"},
		{ "id":"30","Name":"Nick","Surname":"Nick","Maths":"10","Physics":"19","Chemistry":"20","Biology":"17","Absences":"0","Papers":"2"},
		{ "id":"31","Name":"Nick","Surname":"Nick","Maths":"20","Physics":"17","Chemistry":"11","Biology":"17","Absences":"20","Papers":"8"},
		{ "id":"32","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"33","Name":"Nick","Surname":"Nick","Maths":"20","Physics":"17","Chemistry":"11","Biology":"17","Absences":"20","Papers":"8"},
		{ "id":"34","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"35","Name":"Nick","Surname":"Nick","Maths":"17","Physics":"13","Chemistry":"20","Biology":"19","Absences":"35","Papers":"12"},
		{ "id":"36","Name":"Nick","Surname":"Nick","Maths":"12","Physics":"15","Chemistry":"17","Biology":"12","Absences":"12","Papers":"10"},
		{ "id":"37","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"18","Chemistry":"12","Biology":"12","Absences":"15","Papers":"1"},
		{ "id":"38","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"10","Chemistry":"12","Biology":"13","Absences":"21","Papers":"0"},
		{ "id":"39","Name":"Nick","Surname":"Nick","Maths":"11","Physics":"20","Chemistry":"20","Biology":"20","Absences":"45","Papers":"20"},
		{ "id":"40","Name":"Nick","Surname":"Nick","Maths":"19","Physics":"18","Chemistry":"14","Biology":"16","Absences":"8","Papers":"5"},
		{ "id":"41","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"17","Chemistry":"16","Biology":"18","Absences":"9","Papers":"8"},
	    { "id":"42","Name":"Nick","Surname":"Nick","Maths":"20","Physics":"17","Chemistry":"11","Biology":"17","Absences":"20","Papers":"8"},
		{ "id":"43","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"44","Name":"Nick","Surname":"Nick","Maths":"17","Physics":"13","Chemistry":"20","Biology":"19","Absences":"35","Papers":"12"},
		{ "id":"45","Name":"Nick","Surname":"Nick","Maths":"18","Physics":"10","Chemistry":"17","Biology":"11","Absences":"56","Papers":"12"},
		{ "id":"46","Name":"Nick","Surname":"Nick","Maths":"11","Physics":"20","Chemistry":"20","Biology":"20","Absences":"45","Papers":"20"},
		{ "id":"47","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"16","Chemistry":"8","Biology":"17","Absences":"21","Papers":"9"},
		{ "id":"48","Name":"Nick","Surname":"Nick","Maths":"17","Physics":"13","Chemistry":"20","Biology":"19","Absences":"35","Papers":"12"},
		{ "id":"49","Name":"Nick","Surname":"Nick","Maths":"12","Physics":"15","Chemistry":"17","Biology":"12","Absences":"12","Papers":"10"},
		{ "id":"50","Name":"Nick","Surname":"Nick","Maths":"15","Physics":"18","Chemistry":"12","Biology":"12","Absences":"15","Papers":"1"},
		{ "id":"51","Name":"Nick","Surname":"Nick","Maths":"16","Physics":"10","Chemistry":"12","Biology":"13","Absences":"21","Papers":"0"},
		{ "id":"52","Name":"Nick","Surname":"Nick","Maths":"11","Physics":"20","Chemistry":"20","Biology":"20","Absences":"45","Papers":"20"}
		]
});
